### ISSUE TITLE
MCVF causing crashes when hunting with weapons from Rimsenal? 

### ISSUE THREAD

**Issue by II-ELIF-II** [Vanilla-Expanded/VanillaExpandedFramework#1]
> Exception in RimWorld.ThinkNode_ConditionalCanDoConstantThinkTreeJobNow TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
>   at MVCF.VerbManager.<get_CurrentlyUseableRangedVerbs>b__14_0 (MVCF.ManagedVerb v) [0x00000] in <e52aaa923c214632b956e537d17223b7>:0 
>   at System.Linq.Enumerable+WhereListIterator`1[TSource].MoveNext () [0x00037] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
>   at MVCF.Utilities.TargetFinder.BestAttackTarget (Verse.AI.IAttackTargetSearcher searcher, Verse.Verb& verbUsed, Verse.AI.TargetScanFlags flags, System.Predicate`1[T] validator, System.Single minDist, System.Single maxDist, Verse.IntVec3 locus, System.Single maxTravelRadiusFromLocus, System.Boolean canBashDoors, System.Boolean canTakeTargetsCloserThanEffectiveMinRange, System.Boolean canBashFences, System.Boolean setCurrent, System.Boolean canMove) [0x0012f] in <e52aaa923c214632b956e537d17223b7>:0 
>   at (wrapper dynamic-method) RimWorld.JobGiver_ConfigurableHostilityResponse.RimWorld.JobGiver_ConfigurableHostilityResponse.TryGetAttackNearbyEnemyJob_Patch0(RimWorld.JobGiver_ConfigurableHostilityResponse,Verse.Pawn)
>   at RimWorld.JobGiver_ConfigurableHostilityResponse.TryGiveJob (Verse.Pawn pawn) [0x00043] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at Verse.AI.ThinkNode_JobGiver.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00000] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00022] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**and**

> Iris threw exception in WorkGiver HunterHunt: System.NullReferenceException: Object reference not set to an instance of an object
>   at (wrapper dynamic-method) Verse.ShotReport.Verse.ShotReport.HitReportFor_Patch1(Verse.Thing,Verse.Verb,Verse.LocalTargetInfo)
>   at MVCF.ManagedVerb.GetScore (Verse.Pawn p, Verse.LocalTargetInfo target, System.Boolean debug) [0x00079] in <e52aaa923c214632b956e537d17223b7>:0 
>   at MVCF.VerbManager.ChooseVerb (Verse.LocalTargetInfo target, System.Collections.Generic.List`1[T] options) [0x001df] in <e52aaa923c214632b956e537d17223b7>:0 
>   at MVCF.Utilities.PawnVerbUtility.BestVerbForTarget (Verse.Pawn p, Verse.LocalTargetInfo target, System.Collections.Generic.IEnumerable`1[T] verbs) [0x0000e] in <e52aaa923c214632b956e537d17223b7>:0 
>   at MVCF.Patch_Pawn_TryGetAttackVerb.AttackVerb (Verse.Pawn pawn, Verse.Thing target, System.Boolean allowManualCastWeapons) [0x001fa] in <e52aaa923c214632b956e537d17223b7>:0 
>   at MVCF.Patch_Pawn_TryGetAttackVerb.Prefix (Verse.Verb& __result, Verse.Pawn __instance, Verse.Thing target, System.Boolean& __state, System.Boolean allowManualCastWeapons) [0x00001] in <e52aaa923c214632b956e537d17223b7>:0 
>   at (wrapper dynamic-method) Verse.Pawn.Verse.Pawn.TryGetAttackVerb_Patch3(Verse.Pawn,Verse.Thing,bool,bool)
>   at RimWorld.WorkGiver_HunterHunt.CanFindHuntingPosition (Verse.Pawn hunter, Verse.Pawn animal) [0x00018] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at RimWorld.WorkGiver_HunterHunt.HasJobOnThing (Verse.Pawn pawn, Verse.Thing t, System.Boolean forced) [0x000a8] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at RimWorld.JobGiver_Work+<>c__DisplayClass3_1.<TryIssueJobPackage>b__0 (Verse.Thing t) [0x00013] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at Verse.GenClosest+<>c__DisplayClass2_0.<ClosestThingReachable>b__0 (Verse.Thing t) [0x00034] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at Verse.GenClosest.<ClosestThing_Global>g__Process|5_0 (Verse.Thing t, Verse.GenClosest+<>c__DisplayClass5_0& ) [0x00047] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at Verse.GenClosest.ClosestThing_Global (Verse.IntVec3 center, System.Collections.IEnumerable searchSet, System.Single maxDistance, System.Predicate`1[T] validator, System.Func`2[T,TResult] priorityGetter) [0x00125] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at Verse.GenClosest.ClosestThingReachable (Verse.IntVec3 root, Verse.Map map, Verse.ThingRequest thingReq, Verse.AI.PathEndMode peMode, Verse.TraverseParms traverseParams, System.Single maxDistance, System.Predicate`1[T] validator, System.Collections.Generic.IEnumerable`1[T] customGlobalSearchSet, System.Int32 searchRegionsMin, System.Int32 searchRegionsMax, System.Boolean forceAllowGlobalSearch, Verse.RegionType traversableRegionTypes, System.Boolean ignoreEntirelyForbiddenRegions) [0x0014c] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0 
>   at RimWorld.JobGiver_Work.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x004be] in <2ac9ff1464ea49a284d37555c9c1f6ec>:0  
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Player Log:** [Player.txt](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/files/9847074/Player.txt)

**Comment by II-ELIF-II** [comment]
So an update, the think tree issue seems to be coming from the Fishing mod, however I do have additional details on what causes the crashing when hunting, it seems to occur when using a weapon that was crafter/bought, this prevents the pawn from attacking enemies automatically, and crash the game when attempting to hunt.

**Comment by legodude17** [comment]
Cannot reproduce. It appears something is interfering with MVCF saving and loading verbs.

**Comment by II-ELIF-II** [comment]
Apparently, it takes a while for it to occur, a friend of mine just started reporting the same issue after playing for a while, perhaps it breaks down somewhere down the line? anything I can do to help test and track it down?

**Comment by II-ELIF-II** [comment]
Huh the new update seems to have fixed it on my end, played for a couple hours straight and it just works now, thanks for the update!

**Comment by legodude17** [comment]
Glad it works now!
