### ISSUE TITLE
Massive performance issue with MVCF.Patch_Pawn_TryGetAttackVerb:Prefix

### ISSUE THREAD

**Issue by victorguima** [Vanilla-Expanded/VanillaExpandedFramework#12]
![image](https://user-images.githubusercontent.com/43277299/201731023-159cc91b-b047-465c-aa3c-1df511517a39.png)
Here's a screenshot from Dubs Performance Analyzer.
I'm getting a "Upload Error: HTTP/1.1 400 Bad Request" error from Hugslib and couldn't upload a log. Here's a Player.log instead
[Player.log](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/files/10005792/Player.log)

I'm using the release version that was posted today for testing with Alpha Genes: https://github.com/Vanilla-Expanded/VanillaExpandedFramework/releases/tag/141122

**Comment by legodude17** [comment]
Check the stack trace, also try waiting until the caravans leave. More pawns = worse performance, no matter how well optimized something is.

**Comment by legodude17** [comment]
More than 2 weeks since last comment, closing as abandoned.
