### ISSUE TITLE
Wiki for MVCF needs updating

### ISSUE THREAD

**Issue by Caaz** [Vanilla-Expanded/VanillaExpandedFramework#13]
Seems https://github.com/Vanilla-Expanded/VanillaExpandedFramework/wiki/Multi-Verb-Combat-Framework is out of date, with the deprecation of Features for ActiveFeatures.

A question I have is: Are there no changes other than renaming a field?

**Comment by legodude17** [comment]
I am aware, but I have not gotten around to it.

> A question I have is: Are there no changes other than renaming a field?

It was actually a near-complete rewrite. There were a very large amount of changes.

**Comment by legodude17** [comment]
Wiki should be up to date now!
