### ISSUE TITLE
Mortars during a raider siege seem to be unable to fire

### ISSUE THREAD

**Issue by tenguin** [Vanilla-Expanded/VanillaExpandedFramework#17]
fumo_gaming first brought this up, but during my own mod testing, it can be reproduced and confirmed by me.

This bug can be reproduced consistently even in a new game with no other mods.

It seems that the mortars from a raider siege, after being built and manned, will behave as if no targets are available despite clear line of sight, proper range, and having ammo/manned.

**Reproduction conditions:**
Rimworld 1.4.3555, all dlc enabled.
Entire mod folder deleted and redownloaded from Steam to ensure clean files.
Running only Harmony, Hugslib, VEF, and VAE:Accessories
Hugslogs: https://pastebin.com/9Hh9jv9R

Create a new game using crashlanded, standard settings.
Start enemy RoughOutlander/YttakinPirate raid with Siege via dev menu.

Enemy Mortars will often behave as if no targets are avaialble despite clear line of sight, proper range, and having ammo/manned. fumo_gaming reported that they could target buildings but not pawns, I only tested on pawns. 

This exact problem happens to several mods using VEF, confirmed also having this same problem is VAE:Cave Animals and/or Alpha Animals.

If no mods are enabled, mortars fire normally using exact same conditions.
If VEF is run alone with no other mods, mortars fire normally using exact same conditions.
If VEF is run with Accessories, Cave, or Alpha, mortars are often unable to fire.

Annoyingly, there are no errors or warnings thrown in the logs, but due to reproducibility, the most likely common link is VEF.

I didn't notice this problem back in RW 1.3, so it seems related to a change in 1.4.

**Comment by Skullywag** [comment]
This is probably related to the MCVF issues that are ongoing (pawns shooting with no guns equipped, pawns targetting dead bodies etc) it seems that the area of the code around finding best targets is having issues and these issues only occur if you have the VEF and any mod that allows MCVF to apply its patches active (like caves for example).

**Comment by legodude17** [comment]
What “ongoing issues”? I’ve never been able to reproduce any of those. Anyway, I will investigate this tomorrow.

**Comment by legodude17** [comment]
Fixed in [7d8b09](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/commit/7d8b09cf1ea9f5cd59aa802259e27ef5f5d90e19).
