### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [Vanilla-Expanded/VanillaExpandedFramework#19]
Getting this error when right clicking on Xenogerm which in container
[https://gist.github.com/HugsLibRecordKeeper/61af72bad972af74797211873bdbaccc](steam://openurl_external/https://steamcommunity.com/linkfilter/?url=https://gist.github.com/HugsLibRecordKeeper/61af72bad972af74797211873bdbaccc)

**Comment by legodude17** [comment]
Did you remove mods from a save?

**Comment by legodude17** [comment]
Closing for nonresponse.
