### ISSUE TITLE
Manhunting Animals Don't use VE abilitydefs.

### ISSUE THREAD

**Issue by ottersholdhands** [Vanilla-Expanded/VanillaExpandedFramework#20]
Testing done using Vanilla Rimworld Warg animal and Vanilla Genetics Expanded Pounce Ability. 

       <li>GR_Pounce</li>
       
Warg will use their Pounce ability when trained by player or in a raid. They will however not use it when under the mental state manhunter. Tested Pounce ability on a manhunting Pirate Pawn and it used it perfectly fine. This issue seems to be isolated to Animals that are manhunting.
![206606994-4973ba83-4831-4627-b907-584c013e6531](https://user-images.githubusercontent.com/61456277/207767354-fca4a277-a779-4c81-9e7b-a2d3b9dd191d.jpg)

**Comment by legodude17** [comment]
Try activating the ranged animals function for MVCF.

**Comment by legodude17** [comment]
Closing as abandoned.
