### ISSUE TITLE
Pipe Framework Ratio Wrong on ConvertThingToResource

### ISSUE THREAD

**Issue by Brent-Kerman** [Vanilla-Expanded/VanillaExpandedFramework#22]
I tried make a little mod to learn-by-doing to bottle 75 helixien gas into 1 helixien gas bottle. That works great for the tap. Then I tried to do the drain. I set ratio to 75, and it didn't work. A little testing later I find it wants to take 75 bottles to make 1 gas...which is wrong. https://github.com/Vanilla-Expanded/VanillaExpandedFramework/wiki/CompProperties_ConvertThingToResource shows that the ratio field should work the other way. Take 1 item, make X resource in pipes. I did try a decimal (0.01), to see if i could get it to turn one item into multiple pipe resource (as intended by ratio) and it did not work. I also tried using 0.1 resource to spawn 1 item, also fails, but I expect thats intended behavior, decimals not allowed. The bug is that ratio is working backwards in ConvertThingToResource

**Comment by KylianB** [comment]
Fixed in [db9c0e8](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/commit/db9c0e8e04f385474703a80d39c1a6345649efd1). Closing.
