### ISSUE TITLE
Ability autocasting not working properly on some abilities. Possibly related to MVCF

### ISSUE THREAD

**Issue by ShauaPuta** [Vanilla-Expanded/VanillaExpandedFramework#25]
I was developing a custom summon ability for one of my mods when I noticed that the AI could not cast the ability. They would try, give a null reference exception regarding the jobdriver in the log, and try again. 
I tried another mod I was sure worked, Alpha Animal's VE psycast addon, and their summon abilities could also not be AI casted with the same issue. Also tried with another mod, one of mine jump abilities, and they would also fail AI casting most times.
Projectile abilities work fine.
Manual casting works, but the job gets cancelled and overriden by ranged verbs.

I talked briefly with erdelf over HAR discord, and they said nothing has changed on the abilities part, and the error seemed to be related to MVCF instead. So am here to report.

This is the error every pawn gives when trying to cast an ability:

Exception in JobDriver tick for pawn Cosme driver=JobDriver_AttackStatic (toilIndex=1)
System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.AI.JobDriver_AttackStatic+<>c__DisplayClass4_0.<MakeNewToils>b__1 () [0x0012b] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at Verse.AI.JobDriver.DriverTick () [0x00163] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by legodude17** [comment]
Please provide a full HugsLib log.

**Comment by ShauaPuta** [comment]
A yes, forgot
Here, from game start, to a pawn trying to autocast 
https://gist.github.com/e1ea1503a87147aa3b1bddefa843b1d5

**Comment by legodude17** [comment]
It seems like you have an outdated version of MVCF. The patch that most likely throws that error has been removed for some time.

**Comment by legodude17** [comment]
Closing for abandonment.
