### ISSUE TITLE
Allow manual refill on pipenet CompResourceStorage is reset on load.

### ISSUE THREAD

**Issue by Zeracronius** [Vanilla-Expanded/VanillaExpandedFramework#28]
For some reason, the toggle button for marking a CompResourceStorage as manually refillable is reset after a reload.
This is despite the value seemingly being exposed correctly.

Before reload:
![billede](https://user-images.githubusercontent.com/64704191/221413586-ca6ba480-2a44-4f10-9020-a74defa9cb6b.png)

After reload:
![billede](https://user-images.githubusercontent.com/64704191/221413614-e33fd49d-1323-45e0-8ddb-7689e6b49389.png)

No errors on loading.
https://gist.github.com/HugsLibRecordKeeper/8e24a67f517ed5fc353358168773ce1a

**Comment by KylianB** [comment]
Thank you, fixed in [PipeSystem: save value fix](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/commit/22b97269926527c543d1d5301116ee20775090f2)
