### ISSUE TITLE
Error message on launch

### ISSUE THREAD

**Issue by Cytronvert** [Vanilla-Expanded/VanillaExpandedFramework#30]
Hello, after installing the mod I have an error message at startup on debug-log.
I really have a lot of mods installed but so far there was no problem.

I searched a bit on the internet and I did not find anything except the order in the list of mods but that does not change the problem.

Here are the logs : https://gist.github.com/HugsLibRecordKeeper/706a99549a32b5379f96613ed5753281

Thanks for your help and your work 

PS : Sorry for my bad level in english....

**Comment by legodude17** [comment]
You’re like 4 rimworld versions behind. Update your game.

**Comment by Cytronvert** [comment]
wow quick answer thank you !
I try and I come back
