### ISSUE TITLE
Vanilla Expanded Framework makes the game not spawn any factions

### ISSUE THREAD

**Issue by NPCLeon** [Vanilla-Expanded/VanillaExpandedFramework#31]
[Player.log](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/files/10951872/Player.log)
a little help guys?
(im new to github so sorry if im doing something wrong)

**Comment by juanosarg** [comment]
Your RW version is very, very outdated

**Comment by NPCLeon** [comment]
> Your RW version is very, very outdated

Thats it? daaaaamn... im an idiot

**Comment by legodude17** [comment]
Closing for lack of response.
