### ISSUE TITLE
MVCF Wiki - 2 examples have incorrect namespaces listed

### ISSUE THREAD

**Issue by BBLKepling** [Vanilla-Expanded/VanillaExpandedFramework#41]
Examples:
https://github.com/Vanilla-Expanded/VanillaExpandedFramework/wiki/Examples#hediff-verb-and-drawing-and-independent-fire
https://github.com/Vanilla-Expanded/VanillaExpandedFramework/wiki/Examples#equipment

Source:
https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/main/Source/MVCF/VerbComps/VerbComp_Turret.cs

`<li Class="MVCF.Comps.VerbCompProperties_Turret">`
`<compClass>MVCF.Comps.VerbComp_Turret</compClass>`

should be

`<li Class="MVCF.VerbComps.VerbCompProperties_Turret">`
`<compClass>MVCF.VerbComps.VerbComp_Turret</compClass>`

**Comment by legodude17** [comment]
Fixed, thanks for pointing this out!
