### ISSUE TITLE
[Bug]: VEF and CE compatability. Artillery rockets/Large fragments heavy lag.

### ISSUE THREAD

**Issue by IDKCRI** [Vanilla-Expanded/VanillaExpandedFramework#46]
Rimworld version: 1.4.3704
Combat Extended version: Dev Snapshot from Jun 5, 2023
Combat Extended source (Steam, GitHub, etc.): Git
Vanilla Expanded Framework: All latest versions (Main and mvcf2.5 from Git, Steam release latest version)
Operating system: Win10

Mod list:
[Mod list length: 9]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
Biotech [Official DLC] [https:// no link (local mod)]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
Combat Extended [https:// no link (local mod)]
Turret Collection (Unofficial) [https://steamcommunity.com/sharedfiles/filedetails/?id=2556772185]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]

**Description**
When using (in particular) Multi-barrel rocket launcher from Turret Collection (Unofficial) for testing purposes, there is a strong lag when landing missiles and generating fragments. No error logs, just severe lags and TPS/FPS drop. Without VEF there is no such significant drop in perfomance.

**UPD**
Also, here's two more facts that I've found:
1) When I've experimented with different biomes, I noticed that there's a bit less stutter when it almost empty (like desert one) and stronger one in populated ones (like Temperate Forest with more objects and entities)
2) CPU usage is kinda odd with this, 0 and 1 cores are almost not used during these calculations, but cores 2 and 3 are spike loaded to 100%.

**To reproduce**
Spawn 3 turrets (for better results I'm using Multi-barrel rocket from Turret Collection (Unofficial), but Vanilla 81mm mortar or Rocketswarm launchers works as well), set for them forced target simultaneously and enjoy the results.

**Screenshots & log dumps**
Screenshots bellow, no logs cuz no errors as you can see for yourself.

**With VEF in mod list:**
![With VEF BulletCE Tick](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/94ed3c8b-c8bd-41fd-b4c3-82244cfbfad6)
![With VEF CPU usage](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/6dae0a98-974e-456f-823b-aa9e7ea396be)
![With VEF Fragment Tick](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/eb44d810-ca30-4b0b-ad39-0df4e10110bf)
![With VEF Single Tick](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/267b078b-6137-4618-b3d5-e59211ab6f37)

**Without VEF in mod list:**
![Without VEF BulletCE Tick](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/ee8b1cae-98d6-44f8-9a42-f7a1ccc3569a)
![Without VEF Fragment Tick](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/28da10f2-5cf4-41fa-b53a-e1f99d3ad0f9)
![Without VEF Single Tick](https://github.com/CombatExtended-Continued/CombatExtended/assets/135836489/203106de-8e4d-44d5-971d-4a376463a42d)

**Comment by legodude17** [comment]
Does this occur if you remove CE?

**Comment by IDKCRI** [comment]
No, it's not. So combo-wombo is:
1. CE + VEF -> Heavy lag
2. Only CE -> No lag 
3. Only VEF -> No lag

**Comment by IDKCRI** [comment]
Yes, just checked, CE team already have fixed this case and implemented it in main branch few days ago (https://github.com/CombatExtended-Continued/CombatExtended/pull/2525). I guess gig closed.

**Comment by IDKCRI** [comment]
Yes, just checked, CE team already have fixed this case and implemented it in main branch few days ago (https://github.com/CombatExtended-Continued/CombatExtended/pull/2525). I guess gig closed.

**Comment by legodude17** [comment]
Awesome!
