### ISSUE TITLE
CompProperties_ShieldBubble It's broken

### ISSUE THREAD

**Issue by ffftian** [Vanilla-Expanded/VanillaExpandedFramework#6]
In version 1.3, there is no problem
1.4 I don't know why there is a problem

XML error: <comps><li Class="VFECore.CompProperties_ShieldBubble"><EnergyShieldRechargeRate>0.003</EnergyShieldRechargeRate><EnergyShieldEnergyMax>30</EnergyShieldEnergyMax></li></comps> doesn't correspond to any field in type PawnKindDef. Context: <PawnKindDef ParentName="SZ_BaseHeavenForgedKind"><defaultFactionType>SZ_HeavenForgedCelestiall</defaultFactionType><aiAvoidCover>true</aiAvoidCover><destroyGearOnDrop>true</destroyGearOnDrop><defName>SZ_HeavenForgedRanger</defName><label>神铸轻车</label><race>Mech_Lancer</race><combatPower>150</combatPower><lifeStages><li><bodyGraphicData><texPath>Things/Pawn/HeavenForged/HeavenForgedRanger</texPath><graphicClass>Graphic_Multi</graphicClass><drawSize>1.5</drawSize><shadowData><volume>(0.4, 0.8, 0.4)</volume></shadowData></bodyGraphicData></li></lifeStages><weaponMoney>9999~9999</weaponMoney><weaponTags><li>SZ_HeavenForged_Melee</li></weaponTags><comps><li Class="VFECore.CompProperties_ShieldBubble"><EnergyShieldRechargeRate>0.003</EnergyShieldRechargeRate><EnergyShieldEnergyMax>30</EnergyShieldEnergyMax></li></comps></PawnKindDef>
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlToObject:ObjectFromXml<Verse.PawnKindDef> (System.Xml.XmlNode,bool)
Verse.DirectXmlToObject:ObjectFromXmlReflection<Verse.PawnKindDef> (System.Xml.XmlNode,bool)
Verse.DirectXmlLoader:DefFromNode (System.Xml.XmlNode,Verse.LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML (System.Xml.XmlDocument,System.Collections.Generic.Dictionary`2<System.Xml.XmlNode, Verse.LoadableXmlAsset>)
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by ffftian** [comment]
XML error: <comps><li Class="VFECore.CompProperties_ShieldBubble"><EnergyShieldRechargeRate>0.003</EnergyShieldRechargeRate><EnergyShieldEnergyMax>30</EnergyShieldEnergyMax></li></comps> doesn't correspond to any field in type PawnKindDef.

**Comment by ffftian** [comment]
XML error: <comps><li Class="VFECore.CompProperties_ShieldBubble"><EnergyShieldRechargeRate>0.003</EnergyShieldRechargeRate>
<EnergyShieldEnergyMax>30</EnergyShieldEnergyMax></li>
</comps> doesn't correspond to any field in type PawnKindDef.

**Comment by ffftian** [comment]
XML error: <comps><//li Class="VFECore.CompProperties_ShieldBubble"><//EnergyShieldRechargeRate>0.003<///EnergyShieldRechargeRate><//EnergyShieldEnergyMax>30</EnergyShieldEnergyMax></li></comps> doesn't correspond to any field in type PawnKindDef.

**Comment by Taranchuk** [comment]
You need to add the comp to ThingDef of following pawn, not to PawnKindDef
