### ISSUE TITLE
Icon stays after building deconstruction

### ISSUE THREAD

**Issue by databobek** [Vanilla-Expanded/VanillaExpandedFramework#62]
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/8420ef23-7a51-416a-b918-38bfb3939da6)
set to transfer content, deconstructed

**Comment by KylianB** [comment]
Should already be fixed with [this commit](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/commit/620449360dfdc3aac9d5809d4ab73654283f3b67)
Please try with the github version and let me know. It will be published on steam soon.

**Comment by databobek** [comment]
Seems to work!
