### ISSUE TITLE
Can't prioritize construction unless assigned to art

### ISSUE THREAD

**Issue by deadhitter1** [Vanilla-Expanded/VanillaExpandedFramework#67]
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/25663592/f02842fb-8dc8-442d-8ac1-5ad15ea2e113)
https://pastebin.com/ASRPgHx7
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/25663592/cd8aaa5b-65c1-4b61-a1cd-fbe662f1979f)

Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at VFECore.**WorkGiver_ConstructionSkill**_FinishFrames.JobOnThing (Verse.Pawn pawn, Verse.Thing t, System.Boolean forced) [0x00025] in <a1a14f177044408ea12115cc713b9cc2>:0

Somebody with this modlist also has this problem:
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/25663592/bac1025d-5af0-4e2d-a007-baa1fd760717)

**Comment by erdelf** [comment]
fixed in https://github.com/Vanilla-Expanded/VanillaExpandedFramework/commit/89926391c26ebffec2115c5dbd6662283bd318f5
