### ISSUE TITLE
HumanlikeMeshPoolUtility Transpilers prevent other mods scaling pawn size

### ISSUE THREAD

**Issue by oorzkws** [Vanilla-Expanded/VanillaExpandedFramework#7]
I'm inexperienced with reading transpilers so I'm hoping you can help some here. Having VEF active results in [other mods](https://github.com/emipa606/VariedBodySizes/blob/main/Source/VariedBodySizes/Graphic_MeshAt.cs) no longer being able to scale pawn body sizes. The heads still scale, but the body no longer does.

This is fairly simple to replicate, but I'm not able to parse enough of the transpiler changes to make sense of which mod would need to adjust for this. Relevant VEF code is below, disabling this patch allows pawn scaling to function fine in testing.

https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/5a90fbbebd91cf2bb8cf018bfc05fde6f1b3a171/Source/VFECore/VFECore/HarmonyPatches/PawnRenderer_Patches.cs#L280-L361

**Comment by oorzkws** [comment]
Addendum: looks like most of the patches in this file have similar behavior, i.e. clothes don't scale with VEF present.

**Comment by oorzkws** [comment]
After taking a few days to learn transpilers, I think the issue is mainly that the stack is cleared where VEF inserts. It would be better for compatibility if it instead considered the state of the function. 

original:
```cs
		public static GraphicMeshSet GetHumanlikeBodySetForPawn(Pawn pawn)
		{
			if (ModsConfig.BiotechActive && pawn.ageTracker.CurLifeStage.bodyWidth != null)
			{
				return MeshPool.GetMeshSetForWidth(pawn.ageTracker.CurLifeStage.bodyWidth.Value);
			}
			return MeshPool.humanlikeBodySet;
		}
```

With current VEF (approximation)
```
		public static GraphicMeshSet GetHumanlikeBodySetForPawn(Pawn pawn)
		{
			if (ModsConfig.BiotechActive && pawn.ageTracker.CurLifeStage.bodyWidth != null)
			{
				var MeshSet = MeshPool.GetMeshSetForWidth(pawn.ageTracker.CurLifeStage.bodyWidth.Value); // Not actually a local, just showing the discard process
				return updatedMeshSet(pawn);
			}
			return updatedMeshSet(pawn);
		}
```

Ideal:
```cs
		public static GraphicMeshSet GetHumanlikeBodySetForPawn(Pawn pawn)
		{
			if (ModsConfig.BiotechActive && pawn.ageTracker.CurLifeStage.bodyWidth != null)
			{
				return updatedPawnScale(pawn, pawn.ageTracker.CurLifeStage.bodyWidth.Value); // Function doesn't exist, but would have a type of Vector2 and a signature of (Pawn pawn, float baseSize)
			}
			return updatedPawnScale(pawn, MeshPool.HumanlikeBodyWidth);
		}
```

Alternative ideal, a heavier change but this is calling a builtin function that can then just be postfixed 🚀 
```cs
		public static GraphicMeshSet GetHumanlikeBodySetForPawn(Pawn pawn)
		{
			return updatedPawnScale(pawn, HumanlikeBodyWidthForPawn(pawn));
		}
```

**Comment by Taranchuk** [comment]
Wrong topic, I think.

**Comment by Taranchuk** [comment]
It's not in PawnRenderer.DrawPawnBody

**Comment by oorzkws** [comment]
Yeah, I'll update the OP. It was a guess I was starting from, but ended up being wrong.

**Comment by Taranchuk** [comment]
Ok, please create a new issue in this case.
